### PR TITLE
React: fix assembly labels and gene search 

### LINKED ISSUE #165: React: fix assembly ID display label

### PR DESCRIPTION
**Pull request by hannahle**
- Assembly ID selection now reflects the full form of the reference genome (GChr38/37 instead of 38, 37).
- Before, if the user types in the same gene name as before, no autocomplete results would be shown in the dropdown. Adding `geneName` as a dependency to the `useEffect` hook responsible for setting options in the dropdown fixes this issue.

### CODE REVIEW

File: react/src/components/GeneSearch.tsx [hunk 1]
```diff
@@ -43,6 +63,22 @@ const GeneSearch: React.FC<GeneSearchProps> = ({ assembly, geneName, onChange, o
 
     const debouncedAutocompleteFetch = useAsyncDebounce(fetchAutocompleteResults, 500);
 
+    const formatAutocompleteOptions = useCallback(
+        (autocompleteResults: AutocompleteResults) =>
+            (autocompleteResults.autocompleteResults.hits || [])
+                .filter(hit => !!hit.ensembl?.gene && !!hit.genomic_pos && !!hit.genomic_pos_hg19)
```
Comment (kevinlul) [inline react/src/components/GeneSearch.tsx:60]: Guessing by this that most fields are actually optional for `AutocompleteResults`?

File: server/src/resolvers/getVariantsResolver/utils/resolveAssembly.ts [hunk 2]
```diff
@@ -1,11 +1,6 @@
...
-  } else if (assembly.includes('38')) {
-    return '38';
-  } else {
-    return '';
-  }
-};
+import { AssemblyId } from '../../../types';
+
+const resolveAssembly: (assembly: string) => AssemblyId = assembly =>
+  assembly.includes('38') ? '38' : '37';
```
Comment (kevinlul) [inline server/src/resolvers/getVariantsResolver/utils/resolveAssembly.ts]: Do you have enforce module boundary typings on for this codebase? If not you might be able to make this less confusing by just typing the argument and adding `as const` after the return.

File: react/src/components/GeneSearch.tsx (hunk 1 above)
Comment (hannahle) [reply react/src/components/GeneSearch.tsx:60]: ah yes good catch.
